### PR TITLE
slight adjustments for light mode

### PR DESCRIPTION
**Pull request by stonerl**
Some screenshots for reference:

CleanShot 2023-08-07 at 12 39 40@2x
CleanShot 2023-08-07 at 12 39 23@2x

### CODE REVIEW

**Comment by stonerl** [comment]
should have been a draft

**Comment by joeyballentine** [comment]
A definite improvement over what's there now. I kinda feel like it's just too bright in general though. One thing I've always wanted to try was making the background more or a gray and the nodes lighter rather than the other way around. Would you mind trying that out?

**Comment by stonerl** [comment]
I had to increase brightness to give more contrast to individual elements.

I can try to implement your suggestion. But it could be very difficult since it might sacrifice overall contrast again.

As @RunDevelopment said, since the light theme was an afterthought, it is quite difficult to properly implement it within the current confinements.

In the mid to long run, it would be a good idea to rethink theming and adding more css attributes to have a more nuanced way to theme the app.

I'll set this on my todo list if I find some time.

**Comment by joeyballentine** [comment]
Do you think the changes you have a good enough for now? I'd like to get this in if you think it's ready

**Comment by stonerl** [comment]
> Do you think the changes you have a good enough for now?

Yes, this can go in.

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
