### PR TITLE
Fix NCNN model interpolation execution context

### PR DESCRIPTION
**Pull request by RunDevelopment**
I forgot to enable the context in `register`.

### CODE REVIEW

**Comment by joeyballentine** [comment]
How did the CI's type checking not catch this?

**Comment by RunDevelopment** [comment]
Good question. I also only saw the warning for it sometimes.

**Comment by RunDevelopment** [comment]
CI doesn't install dependencies anymore for some reason... 
https://github.com/chaiNNer-org/chaiNNer/actions/runs/7534729075/job/20509572330

**Comment by joeyballentine** [comment]
wtf

**Comment by RunDevelopment** [comment]
Hasn't been working for half a year, ever since #1866. When I added `--install-builtin-packages`, I forgot to add it to the type check.

**Comment by joeyballentine** [comment]
oops

**Comment by joeyballentine** [comment]
is this good to merge now that #2469 is failing?

**Comment by RunDevelopment** [comment]
Yes.

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
