### PR TITLE
Removed PyTorch scale tag in output

### PR DESCRIPTION
**Pull request by RunDevelopment**
We already removed this for NCNN, so I removed for PyTorch as well.
image

### CODE REVIEW

**Comment by joeyballentine** [comment]
Is there any way we could also move the model arch and the arch type tags to the type tag area as well? Especially since showing the arch type as an input type restriction would be nice

**Comment by RunDevelopment** [comment]
You mean SR vs Face, right?

**Comment by joeyballentine** [comment]
Yes

**Comment by RunDevelopment** [comment]
image

Maybe we should rename the model input of Upscale Face to just "Model"? The "Face SR" is redundant now.

**Comment by joeyballentine** [comment]
Yeah that sounds good to me

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
