### PR TITLE
Added Apply LUT node

### PR DESCRIPTION
**Pull request by RunDevelopment**
image

### CODE REVIEW

**Comment by RunDevelopment** [comment]
@theflyingzamboni I heard that `np.take` is way faster than indexing a LUT like I did here, but I could get this to work. Do you happen to know this?

**Comment by RunDevelopment** [comment]
I change the implementation to always quantize the grayscale image to the size of the LUT. This allows users to achieve color quantization effects that would be hard to achieve otherwise.

image

If users want chainner to smoothly interpolate between LUT values, then they can do that by resizing the LUT themselves using our Resize nodes.

**Review by joeyballentine — APPROVED** [review]

**Comment by joeyballentine** [comment]
LGTM but I'd like to wait until Zamboni responds to your question

**Comment by theflyingzamboni** [comment]
> @theflyingzamboni I heard that `np.take` is way faster than indexing a LUT like I did here, but I couldn't get it to work. Do you happen to know this?

I've never come across that function before. I could try messing around with it and see if I can figure out how it works.

**Comment by theflyingzamboni** [comment]
> Also, we should definitely add a node to create LUTs

Create RGB + Shift 😛

**Comment by joeyballentine** [comment]
> > Also, we should definitely add a node to create LUTs
> 
> Create RGB + Shift 😛

256 of them?? Lmao

**Comment by theflyingzamboni** [comment]
@RunDevelopment Okay, I got `np.take` working, and it is about twice as fast. The issue is LUT dimensionality. The way it is right now, the LUT has dimensions (1, w, c), and for `np.take` to work, it needs to be (w, c).

**Comment by RunDevelopment** [comment]
> so `return np.take(lut, img, axis=0)`.

Doesn't work.

image

```
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 349, in __process
    raw_output, execution_time = await self.loop.run_in_executor(
  File "C:\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 223, in wrapper
    result = supplier()
  File "C:\Users\micha\Git\chaiNNer\backend\src\nodes\nodes\image_utility\lut.py", line 68, in run
    return np.take(lut, img, axis=0)
  File "<__array_function__ internals>", line 5, in take
  File "C:\Python38\lib\site-packages\numpy\core\fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "C:\Python38\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
IndexError: index 72 is out of bounds for axis 0 with size 1
```

**Comment by RunDevelopment** [comment]
Argh, you know what? Let's just not use `np.take` right now. If the node is too slow, we can try to make it faster later.

**Comment by theflyingzamboni** [comment]
@RunDevelopment You didn't correct the dimensions of the LUT.

> The way it is right now, the LUT has dimensions (1, w, c), and for np.take to work, it needs to be (w, c).

**Pull request merged**
