### PR TITLE
Improve missing dependency error logging & UI

### PR DESCRIPTION
**Pull request by joeyballentine**
These logs just end up confusing people who think they have a major problem by bot having the extra deps installed

### CODE REVIEW

**Comment by RunDevelopment** [comment]
I would argue that knowing which deps fail to import is pretty important for us to diagnose errors. This PR will make it so that we also can't see these logs anymore, right?

**Comment by joeyballentine** [comment]
True, unless there's a critical error. The main problem is it logs for every node that fails. Maybe I just add the failing dep to a set and print that at the end

**Comment by RunDevelopment** [comment]
> unless there's a critical error

We define what a critical error is, and I would argue that a dependency failing to import is pretty critical. If the dependency is optional, then it's not critical, of course, but non-optional deps can also fail to import.

> The main problem is it logs for every node that fails. Maybe I just add the failing dep to a set and print that at the end.

Instead, could we log import error (immediately) unless we've seen already? Delaying errors until the end might make it harder to understand the logs.

**Comment by joeyballentine** [comment]
Now, if a critical import error happens for a category that doesn't have an install hint, it will look like this on the frontend:
image

meanwhile optional ones still look like they did before:
image

As for logging, this is what it looks like now:
image

**Review by RunDevelopment — APPROVED** [review]

**Pull request merged**
