### PR TITLE
Fix Color type color not shading properly

### PR DESCRIPTION
**Pull request by joeyballentine**

### CODE REVIEW

**Comment by RunDevelopment** [comment]
The real problem is that we parse those hex colors incorrectly. See `colorTools.ts` -> `hexToRgb`. You could probably just use `parseRgbHex` from `colorUtil` to fix this.

Also, we could probably clean up or color utility...

**Comment by joeyballentine** [comment]
Yeah probably, but this fixes the present issue. Redoing how this works can be a separate pr

**Comment by RunDevelopment** [comment]
This PR isn't a fix but a workaround. Once the real bug is fixed, there's no point in making this change.

**Comment by joeyballentine** [comment]
I don't really care about fixing the actual problem behind this right now. This works. Why not merge it?

**Comment by RunDevelopment** [comment]
Because you're just accumulating tech debt, when the actual fix is pretty simple. Let me make a PR for it.

**Comment by RunDevelopment** [comment]
Actually, let's go. I'm gonna just refactor our color stuff after this.

**Review by RunDevelopment — APPROVED** [review]

**Comment by RunDevelopment** [comment]
Also, what issue was this even fixing? You never mentioned.

**Comment by joeyballentine** [comment]
This was for edges being invisible when you clicked on them

**Pull request merged**
