### PR TITLE
Automatically restart backend on deps changes

### PR DESCRIPTION
**Pull request by RunDevelopment**
Changes:
- The deps manager will automatically restart the backend after (un)installing dependencies.
- Removed "Restart chaiNNer" button from deps manager.
- Everything related to types is not allowed to assume that the schema id of a node is valid.
- While testing, I found that the backend event source is not a good indicator to find out whether the backend is still alive. When restarting the backend, the event source *sometimes* errors (as in, its current state is "error"), but it actually still works just fine. So I demoted the event source error alert to a log warning.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Invalid nodes are automatically removed now, and when the current chain has unsaved changes, we will display another warning.

I also slightly changed alerts so that these "nested" alerts aren't detected as overlapping.

**Comment by joeyballentine** [comment]
Seems like when it removes the nodes it doesn't immediately remove the connected edges. I got two of these warnings 
image

**Comment by RunDevelopment** [comment]
I remove nodes via `removeNodesById`, so removing them likely isn't the problem. Invalid nodes don't have handles, and since they are only removed after schemata changes have been detected, RF will render one frame where the invalid nodes + edges are still present.

I don't think that there is anything I can do about that.

**Comment by joeyballentine** [comment]
ok, thats fine

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
