### PR TITLE
Pixel Blur

### PR DESCRIPTION
**Pull request by harisreedhar**
chaiNNer-pixel_blur-2023-5-4_21-15

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Maybe I'm misreading the code, but won't the dimensions of the output image be a multiple of the given block size? E.g. with an input image of width 100 and a block size of 16, won't the width of the output image be 96?

**Comment by harisreedhar** [comment]
> Maybe I'm misreading the code, but won't the dimensions of the output image be a multiple of the given block size? E.g. with an input image of width 100 and a block size of 16, won't the width of the output image be 96?

You are right. I have added padding.

**Comment by RunDevelopment** [comment]
I have no idea, why the CI fails. Pyright suddenly says that it can't find `numpy.bool8` anymore in totally unrelated files. I thought that it might be that a new numpy version 1.24.3 broke something, but we already have other successful CI runs with 1.24.3, so it's not that.

---

About the node itself: I think the implementation looks fine now, but I'm not sure about the name and category. Is this a blur? I'm not sure. For reference, Paint.net has its Pixelate effect under the Distortion category. Why did you call this node Pixel *Blur*? (I'm not saying it's bad, I just want to know.)

**Comment by harisreedhar** [comment]
Blur literally means making an image unclear and less distinguishable. This node does the same thing, so I put it in the blur category. Different programmes use different names and categories. In Gimp, it is under the blur category called "pixelize," and in Photoshop, it is called "mosaic."

**Comment by joeyballentine** [comment]
> in Photoshop, it is called "mosaic."

It's also not under the blur category, it's in "Pixelate". Tbh I'm not sure what to do here. Pixelation doesn't scream "blur" to me but I can see how it fits in with the idea of obscuring information.

**Comment by harisreedhar** [comment]
Do you have any suggestion?

**Comment by RunDevelopment** [comment]
Maybe we could call the node Pixelate and move it into Image Filters > Misc? We don't have a "Distortion" category yet, so misc seems fitting. I think that the node name should have "pixel" in it somewhere (for searchability), so I'm against calling it "Mosaic."

**Review by RunDevelopment — APPROVED** [review]
Thank you @harisreedhar!

**Pull request merged**
