### PR TITLE
Added Emoji icon support, current time node

### PR DESCRIPTION
**Pull request by jackcarey**
* Introduced allowing single characters if the `icon` attribute on a node has a [Intl.Segmenter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) length of 1 - useful for emoji or other non-latin characters as an alternative to react-icons
* Added URLInput as a generic input. Uses `urllib.parse` and an allowlist to check if a string is a URL and optionally, if it matches a regex pattern. (not used yet, but intended for future use)
* Added a 'Current Datetime' node under `utility\value\` which includes some formatting options. Useful with 'Text Append' to create unique file names every time a flow is run.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Oh no... You picked the worst possible feature to get started with chainner 😄 

Chainner currently assumes that all nodes are deterministic, and returning the current data time is certainly not deterministic. We don't really support non-deterministic nodes right now. See #1677 for more details.

**Comment by jackcarey** [comment]
That's a shame but there are good questions on that issue so I'm happy for this to be closed. Are the Emoji icons something you'd accept on its own? If so, I'll re-submit that separately

**Comment by RunDevelopment** [comment]
> Are the Emoji icons something you'd accept on its own?

I wonder. Emojis have the disadvantage that their appearance is platform dependent, so we lose control over how they are displayed. Platforms may also choose to give them colors on their own and ignore the theme color we set. As I see it, the main advantages of Emojis are that they are easy to pick, and that we don't pay for them (the part of React Icons that we use is 4MB IIRC).

What do you think @joeyballentine?

**Comment by joeyballentine** [comment]
I'm not totally against the emoji icon support in general, but i wouldn't want to use it for any of our built in nodes unless we can guarantee the appearance on all platforms

**Comment by joeyballentine** [comment]
Are we able to set a custom emoji font?

**Comment by jackcarey** [comment]
The display issue could be solved with something like [Noto Color Emoji](https://fonts.google.com/noto/specimen/Noto+Color+Emoji) and it's [black and white fallback](https://fonts.google.com/noto/specimen/Noto+Emoji) to make them consistent. Color can be controlled using [palletes](https://css-tricks.com/colrv1-and-css-font-palette-web-typography/) if you want to get fancy, or plain font color if the monochromatic version is used.

**Comment by RunDevelopment** [comment]
Yup. Let's do it :)

**Comment by jackcarey** [comment]
emoji icons to be modified and re-submitted

**Comment by RunDevelopment** [comment]
Thank you!

**Pull request closed without merging**
