### PR TITLE
Add "tiling" option to text2img and img2img

### PR DESCRIPTION
**Pull request by adodge**
image

image

### CODE REVIEW

**Comment by joeyballentine** [comment]
Is it just labeled as "tiling" in the actual webui? I kinda wonder if we should call it something else like "seamless edges (tiled textures)" or something, to differentiate it from the kind of tiling done during upscaling. But it's not really that important.

Neat feature 👍

**Comment by adodge** [comment]
Good point.  That is what it's called in the webui, but it is actually a bad name.  I changed it to "Seamless Edges"

**Comment by joeyballentine** [comment]
Is this also an option on img2img?

**Comment by adodge** [comment]
It is, and it seems to work there too.

Without seamless textures:

image

With seamless textures:

image

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
