### PR TITLE
Add more doc information for other input types

### PR DESCRIPTION
**Pull request by joeyballentine**
image
image
image
image

### CODE REVIEW

**Comment by RunDevelopment** [comment]
My thoughts in no particular order:

- I like listing dropdown variants.
- We use minimum text length 0 vs 1 inconsistently, so we should probably treat them the same. Also, I don't think that showing min len = 0/1 has much value, because it pretty much means that there is no required minimum length.
- I think we shouldn't show numeric precision. All our number inputs with precision >=1 can deal with any number of decimal digits (I think). As I see it, limiting the number of decimal digits is a pure UI thing, and not part of the function of a node.
- Numeric minimum and maximum are already part of the type, so I don't see why we would repeat it.

About numbers again: if you think that number types are too unclear to new users (and I agree), then we could add tooltips to types that explain them. E.g. `int(10..)` could have the tooltip text "An integer that is at least 10."

**Comment by RunDevelopment** [comment]
image
image


Not the most natural of language.

**Comment by joeyballentine** [comment]
image

**Comment by joeyballentine** [comment]
Assuming this is good now and merging

**Pull request merged**
