### PR TITLE
Update to pyright 1.1.294

### PR DESCRIPTION
**Pull request by RunDevelopment**
This updates to the latest pyright version. What the CI says and what VSCode (pylance) says should be in sync again. This new version is also a lot strict when it comes to None checks, so it found a few useless conditions.

@theflyingzamboni It seems like pyright now fully supports ONNX's types, and so it found a few things. I already fixed `APT` and `TPT`, but it found 4 other issues in onnx_to_ncnn.py as well. Could you please take a look at them? They look like real bugs to me, but that doesn't mean much...

### CODE REVIEW

**Comment by RunDevelopment** [comment]
yo wtf? Why does pyright pass? It shouldn't...

**Comment by RunDevelopment** [comment]
Ah, finally.

**Comment by theflyingzamboni** [comment]
> This updates to the latest pyright version. What the CI says and what VSCode (pylance) says should be in sync again. This new version is also a lot strict when it comes to None checks, so it found a few useless conditions.
> 
> @theflyingzamboni It seems like pyright now fully supports ONNX's types, and so it found a few things. I already fixed `APT` and `TPT`, but it found 4 other issues in onnx_to_ncnn.py as well. Could you please take a look at them? They look like real bugs to me, but that doesn't mean much...

The None checks and TPT/APT stuff was actually already flagging in VSCode, I've just been doing other things. Or do you mean that the CI version was behind?

**Review by theflyingzamboni — DISMISSED** [review]

**Review by joeyballentine — DISMISSED** [review]

**Comment by joeyballentine** [comment]
oh, theres a conflict

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
