### PR TITLE
Added input conditions to docs

### PR DESCRIPTION
**Pull request by RunDevelopment**
This PR adds basic support for showing the condition of conditional inputs in node docs.

Future PRs should aim to improve the visual presentation. Right now, there is a lot of duplication because conditions are typically shared between inputs.

### Examples

image
image
image
image

### CODE REVIEW

**Comment by joeyballentine** [comment]
The fact that both "condition" and the input name are italic is a little odd. IMO those need more contrast

**Comment by RunDevelopment** [comment]
I agree. I initially made them bold, so they look just like input labels, but that was a bit too much IMO.

image

**Comment by joeyballentine** [comment]
Maybe bold with a smaller weight?

**Comment by joeyballentine** [comment]
Might be worth trying making the input names a larger font size and/or more bold or something. idk

**Comment by RunDevelopment** [comment]
I put more space between inputs to make things clearer.

image

**Comment by joeyballentine** [comment]
I think that looks good personally 👍

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
