### PR TITLE
Reload starting nodes on file changes

### LINKED ISSUE #732: Reload starting nodes
We currently run and cache starting nodes. However, this caching assumes that any files referenced by the node input data do not change.

Add a way for users to refresh the starting nodes, so that the cached output is up-to-date. This could either be a simple context menu entry "Refresh" or some kind of auto reloading (which would be nice).

### PR DESCRIPTION
**Pull request by RunDevelopment**
Resolves #732.

The heavy lifting is done by [chokidar](https://github.com/paulmillr/chokidar), which is a pretty popular library for file watching. I just added the `useWatchFiles` hook as a light wrapper around chokidar.

### CODE REVIEW

**Review by joeyballentine — COMMENTED** [review]
what does this do when the file is renamed?

**Comment by RunDevelopment** [comment]
image

The image inside the node still stays the same. Since running the node didn't succeed, the backend cache will also still have the old value. 

As soon as a new file takes that place old the old file, the node reloads again.

**Comment by joeyballentine** [comment]
I feel like it should instead switch the path to be the renamed file. Thoughts?

**Comment by RunDevelopment** [comment]
I feel like it should instead switch the path to be the renamed file.

No. Firstly, we can't detect this. chokidar only gives us events for 'add', 'change', and 'unlink'. Secondly, that is waaay too much magic. No other program I ever used behaves that way.

**Review by joeyballentine — APPROVED** [review]

**Comment by joeyballentine** [comment]
Makes sense

**Pull request merged**
