### PR TITLE
Added seed input and group

### PR DESCRIPTION
**Pull request by RunDevelopment**
I finally got around to adding a "Seed" input for Add Noise. I did this via a new group that just adds a little "Random seed" button to a number input. Adding the button was pretty tricky though. In the end, I did it via an optional prop in `SchemaInput`. Not an elegant solution, but it works.

image

### CODE REVIEW

**Comment by joeyballentine** [comment]
I think the new seed icon would be better off as a shuffle icon than as a dice. I couldn't tell what it was at first

**Comment by RunDevelopment** [comment]
What does a new seed icon look like? Like this
image
image

or like this
image

**Comment by RunDevelopment** [comment]
I used a die because the button generates a random seed.

**Comment by joeyballentine** [comment]
My suggestion was to use a shuffle icon, not a seed icon lol. Shuffle icons are commonly used for buttons that change some kind of random value, i think

**Comment by RunDevelopment** [comment]
Shuffle icons are typically used when you, well, shuffle something, changing its order. This has nothing to do with generating a random seed. I would never expect to get a random number from pressing this icon:
image

I used dice because I saw it in Automatic1111's web UI.

That being said, I also see that the minimalist die icon might be hard to understand when you don't know what it does. 

Maybe as inspiration, Bitwarden uses this icon for generating new passwords:
image

**Comment by RunDevelopment** [comment]
I think the refresh icon kinda works
image

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
