### PR TITLE
ONNX upscale reworked

### PR DESCRIPTION
**Pull request by adegerard**
Draft PR for information

**What has been done**
- removed `change_shape` flag; assume all models are converted from pytorch (or other) but are in BCHW order
- reworked like it has been done for pytorch
- simple tests (CPU only)

**TODO**
- validate with cuda
- check some perf. optimizations
- remove `np2nptensor` and `nptensor2np`?

### CODE REVIEW

**Comment by adegerard** [comment]
>     * removed `change_shape` flag; assume all models are converted from pytorch (or other) but are in BCHW order

Revert this change because rife models (even if not supported by chaiNNer) are using a different order...

**Comment by joeyballentine** [comment]
@adegerard Do you plan to finish this?

**Comment by adegerard** [comment]
Sorry, I forgot.

I ended some tests: I have to check another time grayscale images.
I wonder whether I have to put back the possibility to change from BCHW to BHWC (onnx_auto_split function)
The reason is that is not implemented in pyTorch.
Except for rife onnx models, I found no other models with this property.

I have an implementation which supports this (not commited)
WHat's your opinion?

**Comment by joeyballentine** [comment]
> I found no other models with this property.

Sorry that I didn't give context to this. This is common in models exported from tensorflow

**Review by joeyballentine — APPROVED** [review]
Looks good. Thanks for this 👍

**Pull request merged**
