### PR TITLE
Adds a regex node

### PR DESCRIPTION
**Pull request by ExoPhantasm**
A basic stripped back implementation that does what it needs but I can appreciate that there might be a better format.  

My usage involves BLIP captions and then needing to perform regex modifications on common captioning errors (sci - fi fi fi fi fi etc) or to adjust the output to my needs, for example perhaps you want to change all cakes into bananas. 

This is primarily for stable diffusion users.

regex

### CODE REVIEW

**Comment by joeyballentine** [comment]
Thanks! 

I do wonder if having separate "regex match" and "text replace" nodes would be a bit better and more modular. For example i can see it being useful to extract text via regex without doing a replacement, or replacing text without regex. And then they could be used together to get this functionality.

**Review by RunDevelopment — COMMENTED** [review]
I don't know how I like making Python re the de facto regex language of chainner.

I think my main problem is Python re is not standardized. Put simply, the semantics of how a regex actually behaves are left up to the implementation. While common constructs are documented, many edge cases are not. 
My favorite example of this are unorthodox backreferences. AFAICT, the documentation will not tell you how these 2 regexes behave: `\1(a)`, `(?:(a)|\1{2}){2}`.

**Comment by RunDevelopment** [comment]
Resolves #352.

**Comment by joeyballentine** [comment]
@RunDevelopment what should we do about this PR?

**Comment by RunDevelopment** [comment]
Not sure. It would be a useful node, but there are still a few open questions.

The main open question is which regex engine we want to use. I would like to add support for doing regex operations in the type system, so I would prefer something like re2 or rust's regex. Exponential backtracking in the type system would be pretty bad.

We should also think about the replacement syntax. Python uses `\X` to reference groups and JS uses `$X`, so it's not like there's a standard way of doing this. We already use `{X}` syntax in Text Pattern, so I would err towards that.

**Comment by joeyballentine** [comment]
> The main open question is which regex engine we want to use

I say we should just pick one and roll with it. I'd rather this PR get finished and merged than stay open forever.

I'm also good with the {} syntax for replacement

**Comment by RunDevelopment** [comment]
The let's just go with re2 for now. Changing that in the future might be a breaking change, but whatever.

**Comment by RunDevelopment** [comment]
Wait, we have chainner_ext now. Let's just use Rust regex. This would allow us to run regexes in the type system since we already use Rust regex in the frontend.

**Comment by RunDevelopment** [comment]
Closed in favor of #1893.

**Pull request closed without merging**
