### PR TITLE
Throttle iterator progress updates

### PR DESCRIPTION
**Pull request by joeyballentine**
I realized while testing #2158 that the frontend displays a maximum update depth warning when you run an iterator that is so fast it sends constant updates. I used the existing useBatchedCallback hook that we use for regular node updates and applied it to the iterator one. This fixed the problem.

I'm guessing this might also help improve CPU load when running iterators, maybe.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
> I realized while testing https://github.com/chaiNNer-org/chaiNNer/pull/2158 that the frontend displays a maximum update depth warning when you run an iterator that is so fast it sends constant updates. I used the existing useBatchedCallback hook that we use for regular node updates and applied it to the iterator one. This fixed the problem.

This doesn't make any sense. `useBatchedCallback` does not reduce the number of calls, it just batches them (= waiting for a few to come in and then executing them all at once). So if too many calls were the problem, how does `useBatchedCallback` help?

**Comment by joeyballentine** [comment]
I'm not really sure how, but it does. I could have made it actually throttle the updates, but this worked so I didn't question it. If you think an actual throttle would be better, I can switch it to that

**Comment by RunDevelopment** [comment]
Yeah, throttle would probably be better. Make sure throttle throws away previous events though. I'm not sure whether it will use the first or last event.

**Comment by joeyballentine** [comment]
done

**Review by RunDevelopment — APPROVED** [review]

**Pull request merged**
