### PR TITLE
Improve Video Frame Iterator: codec/container/audio/additional parameters

### PR DESCRIPTION
**Pull request by adegerard**
**Motivation**
- Replace the videotype to let the user choose encoder/container
- Add a textfield to allow the user enter custom parameters #2151 
- The container dropdown is dynamically updated when selecting an encoder

video_frame_iterator

**Limitation and choices**
- No validation of the advanced parameters before execution. _Reason: too many options, parsing in Navi would be very complicated_

**Other**
- complexity of the implementation: it seems it is not currently possible to create a dropdown depending on the encoder value.

**This is a draft, please give feedback (here or on Discord)**

### CODE REVIEW

**Comment by adegerard** [comment]
**Modifications vs 1st draft**
- Removed HEVC (=H265)
- Added .mov container
- Remove encoders for the (very old) avi container
- Changed the `audio` checkbox by dropdown: items and behavior similar to Topaz

**Tests**
 - with a MPEG2/PCM video file: every combination
 - mp4, does not allow PCM audio, verified that the error is reported in the log file
 - Checked a few additional parameters

**Known issues**
- extra spaces and linefeed in `additional parameters` generates an error

video_frame_iterator_options

**Review by joeyballentine — APPROVED** [review]
This is great and seems to work well, including the additional parameters. Thanks for taking the time to do this!

**Comment by joeyballentine** [comment]
Whoops, sorry about that migration conflict. Should be pretty easy to resolve though

**Review by joeyballentine — APPROVED** [review]

**Comment by joeyballentine** [comment]
ignore that approval, the CI is failing -- oops

**Comment by adegerard** [comment]
grrr: gihub merge conficts....

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
