### PR TITLE
Fix ESRGAN-2c2 scale detection

### PR DESCRIPTION
**Pull request by joeyballentine**
I was doing a cube root, which worked perfectly fine for 4x, but broke at 2x. Turns out I actually needed to do a /4 then a sqrt.

### CODE REVIEW

**Comment by joeyballentine** [comment]
Would it be better to use math.sqrt for this?

**Comment by RunDevelopment** [comment]
> Would it be better to use math.sqrt for this?

I don't think it really matters. sqrt will be faster, but `** 0.5` is clearer IMO.

---

Nothing issue: Taking the square root doesn't exactly guarantee integers and `int(x)` will truncate. Is rounding down really the intended rounding method? If the result *should* be an integer before truncation, we might get an off-by-one error because the float will be 1.99999999 or something.

**Comment by joeyballentine** [comment]
Oh i thought int rounded to the nearest whole. Should I use math.round then?

**Comment by RunDevelopment** [comment]
Yeah, `round` should be good.

**Review by RunDevelopment — APPROVED** [review]

**Pull request merged**
