### PR TITLE
Update load_video node for more accurate color conversion and chroma reconstruction

### PR DESCRIPTION
**Pull request by mrjschulte**
This PR updates the ffmpeg based load_video node to use a more accurate color decoding and chroma reconstruction path.  

This node now uses lanczos filtering by default and also skips the previously present extra conversion from rgb24 to bgr24 by having ffmpeg send a bgr24 rawvideo pipe natively to chaiNNer

### CODE REVIEW

**Review by joeyballentine — DISMISSED** [review]
Thanks! Videos process with a roughly 1.05x speed increase with this. That, combined with the better filtering, makes this a decent improvement.

**Comment by joeyballentine** [comment]
We use a great package called `ruff` for formatting and linting, which found some small issues with this. This PR will be good to go once those detected issues are fixed. Thanks again!

**Comment by mrjschulte** [comment]
Ok, removed the dead cv2 import so should be good now.

**Review by joeyballentine — APPROVED** [review]

**Comment by adegerard** [comment]
question: sws flags are for scaling, why having added them?

**Pull request merged**
