### PR TITLE
Use RGBa mode for resize and rotate

### LINKED ISSUE #1323: Resizes change transparent colors to black
I suspect that this is PIL optimizing the images for compressed size, but it seems it can cause issues for people working with 3D model textures. Either we need to figure out how to prevent PIL from doing this, or resize color and alpha channels separately.

### PR DESCRIPTION
**Pull request by theflyingzamboni**
Fixes #1323

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Doesn't work for me.

```
[0] [2022-12-02 14:49:10 +0100] [14092] [ERROR] 'RGBa'
[0] Traceback (most recent call last):
[0]   File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 344, in __process
[0]     raw_output, execution_time = await self.loop.run_in_executor(
[0]   File "C:\Python38\lib\concurrent\futures\thread.py", line 57, in run
[0]     result = self.fn(*self.args, **self.kwargs)
[0]   File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 222, in wrapper
[0]     result = supplier()
[0]   File "C:\Users\micha\Git\chaiNNer\backend\src\nodes\nodes\image_dimension\resize_factor.py", line 60, in run
[0]     return resize(img, out_dims, interpolation)
[0]   File "C:\Users\micha\Git\chaiNNer\backend\src\nodes\utils\pil_utils.py", line 63, in resize
[0]     return np.array(pimg).astype("float32") / 255
[0]   File "C:\Python38\lib\site-packages\PIL\Image.py", line 689, in __array__
[0]     shape, typestr = _conv_type_shape(self)
[0]   File "C:\Python38\lib\site-packages\PIL\Image.py", line 270, in _conv_type_shape
[0]     typ, extra = _MODE_CONV[im.mode]
[0] KeyError: 'RGBa'
```

image

**Comment by theflyingzamboni** [comment]
What the hell. How could this work for me and not you? Does it work for you @joeyballentine?

**Comment by joeyballentine** [comment]
works fine for me

**Comment by theflyingzamboni** [comment]
Well, per M's response on the issue and my own testing, this isn't the solution we want anyway.

**Pull request closed without merging**
