### PR TITLE
Add node to remove border/frame with constant color

### PR DESCRIPTION
**Pull request by RunDevelopment**
[Someone asked for this on discord](https://discord.com/channels/930865462852591648/1045361136196919366/1224787134834151506), and I thought this would be a useful feature.

image

This node has a few useful features:
- It automatically detects the frame/border color.
- It allows the user to select which non-frame/border section of the image they want.
- It allows the user to add a padding around the selected section.

The select options have the following effects:
image

The node is also quite useful for cropping images with a constant background color:

image

### CODE REVIEW

**Comment by joeyballentine** [comment]
Is the "crop to content" node still needed after this?

**Comment by RunDevelopment** [comment]
Yes. While the 2 nodes are very similar, they define the "content of the image" differently. Crop to Content only looks at the alpha channel to determine whether a pixel is part of the content of the image. Crop Border looks at the average error of the pixel color to a background color.

This actually the only difference between the 2 nodes. Otherwise, Crop Border is a super set of Crop to Content. I even combined the 2 nodes into Crop to Content while working on this PR, but then discarded it, because the node became too complex. I think new users would have a hard time using this node when the equivalent filters in Gimp and other programs are so much simpler.

image

**Comment by joeyballentine** [comment]
I feel like you don't even have to have separate tabs for them.... "transparent" is just a bg color

**Comment by RunDevelopment** [comment]
> I feel like you don't even have to have separate tabs for them.... "transparent" is just a bg color

That would be a breaking change. 

Right now, Crop To content only considers the alpha channel. Suppose we set an opacity threshold of 50%. Then any pixels with alpha >50% will be considered content, regardless of their RGB values.

However, if we use "transparent" as the border, we'll have to also set its RGB values. So let's say we set the border color to transparent black (RGBA=0,0,0,0), then the absdiff to pixels of transparent white would be ΔRGBA=(1,1,1,0). Despite being fully transparent, this pixel would be considered "content" with a tolerance of 50% due to the large absdiff.

As I said, these 2 nodes define the "content of the image" differently. However, we could change how Crop Border defines it to be compatible with Crop to Content. But I can't think of a useful distance function for that.

And even if we find such a distance function, it would still be a breaking change, because the Crop Border node automatically determines the background/border color. So it even if we have the right distance function for transparent colors, there's no guarantee that the node will pick a transparent color as the background/border color.

**Review by joeyballentine — APPROVED** [review]
never mind then 👍

**Pull request merged**
