### PR TITLE
Added linked inputs group

### PR DESCRIPTION
**Pull request by RunDevelopment**
As mentioned on Discord, I made a group to link the values of inputs. While not perfect, it's functional. The main issue is that values are linked via `inputData`, so sliders aren't synced in real time, but only when a value is entered (slider is released). 

image

---

A for the design: it's not done yet. I'll do it tomorrow.

### CODE REVIEW

**Comment by joeyballentine** [comment]
How hard would it be to add a way to define the relationship between the inputs? For example if one needs to be double the other, of if two linked file paths should have a different extension?

**Comment by RunDevelopment** [comment]
> How hard would it be to add a way to define the relationship between the inputs?

Not very. The only hurdle is that you need to be able to describe this relationship in a JSON-API-compatible way. But we don't need this right now, so why add it?

**Comment by joeyballentine** [comment]
> But we don't need this right now, so why add it?

Specifically I'd like to use that for the NCNN load model node, but I guess it's not too big of a deal right now

**Comment by RunDevelopment** [comment]
Design: 
image

**Comment by joeyballentine** [comment]
> Huh? NCNN Load Model already syncs up .bin and .param

Yeah but I've always wanted to replace that with a generic implementation. Right now it's just hardcoded on the frontend

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
