### PR TITLE
Dilate/Erode node

### PR DESCRIPTION
**Pull request by harisreedhar**
Dilate - Erode operation
chaiNNer-Untitled-2023-2-15_11-43

morph shapes(Rectangle, Ellipse, Cross)
chaiNNer-Untitled-2023-2-15_11-45

### CODE REVIEW

**Review by RunDevelopment — CHANGES_REQUESTED** [review]
Thank you for the PR @harisreedhar!

I wonder whether we should give the node a different name? I had to google what dilate and erode even mean in terms of image processing... 
They turned out to be a simple convolution with min/max. Maybe we could call the node "Min/Max" instead? Photoshop calls these filter "Minimum" and "Maximum" as well. Maybe we could even make 2 nodes for this, like PS. What do you think?

**Comment by joeyballentine** [comment]
I wouldn't just call them "minimum" and "maximum". Maybe "min/max filter" to make it clear that it isn't just a math min/max

**Comment by harisreedhar** [comment]
> Thank you for the PR @harisreedhar!
> 
> I wonder whether we should give the node a different name? I had to google what dilate and erode even mean in terms of image processing... 
> They turned out to be a simple convolution with min/max. Maybe we could call the node "Min/Max" instead? Photoshop calls these filter "Minimum" and "Maximum" as well. Maybe we could even make 2 nodes for this, like PS. What do you think?

Gimp & Blender uses the term ``dilate/erode``.
``Minimum/Maximum`` feels too much generalized🤔
What about ``shrink/grow``?

**Comment by RunDevelopment** [comment]
> Gimp & Blender uses the term `dilate/erode`.

Oh, I didn't know that. In that case, let's keep the name.

**Comment by joeyballentine** [comment]
Agreed

**Comment by harisreedhar** [comment]
@RunDevelopment Should i need to make two separate nodes for each operation?

**Comment by RunDevelopment** [comment]
Yes, I think that would be good.

**Review by RunDevelopment — APPROVED** [review]
Thank you @harisreedhar!

**Pull request merged**
