### PR TITLE
Update to spandrel v0.2.1

### LINKED ISSUE #2461: Pytorch Upscale Image node tiling issue
**Information:**

- Chainner version: [0.21.0]
- OS: [Windows 10]

**Description**
Trying to simple process images through model, however, with tile set to anything lower than 4096 it gives errors at some large images. Workflow preview attached.
image

**Logs**
Error log from interface:
```
Error

An error occurred in a pytorch Upscale Image node:



Input values:
• Image: RGB Image 3900x4680
• Model: Value of type 'spandrel.__helpers.model_descriptor.ImageModelDescriptor'
• Tile Size: Auto (estimate)
• Separate Alpha: No
```
[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/13928974/logs.zip)

### PR DESCRIPTION
**Pull request by RunDevelopment**
Fixes #2461.

This updates spandrel to v0.2.1 and changes our code to take advantage of the new API and guarantees. E.g. since spandrel now handles size requirements, I was able to remove our padding code.

### CODE REVIEW

**Comment by joeyballentine** [comment]
When we update spandrel, we should also always update the link to the supported models section in the readme. I linked to the specific version we use so that it's always correct for whatever chaiNNer currently supports.

**Comment by RunDevelopment** [comment]
Can't we reasonably expect that chainner will always be close to up to date? I don't think it's a huge problem when the spandrel README lists a few archs that chainner will only support in the next release.

**Comment by joeyballentine** [comment]
That's a good point. In that case, can you update it to just point to the normal readme?

**Review by joeyballentine — APPROVED** [review]
actually ill just do it in a separate pr

**Pull request merged**
